GET http://localhost:3000/api/connect
Content-Type: application/json
Authorization: token

## Response:
# {
#   status: "active"
#   subscription_url: string
#   ss_links: {
#     country: string
#     link: string
#   }[]
#   used_traffic: number
#   limit: number | null
#   limit_reset_strategy: string
#   created_at: string
#   expire: string | null
#   online_at: string | null
# }
