openapi: 3.0.0
info:
  title: FRKN API
  description: API for FRKN services
  version: 1.0.0
servers:
  - url: https://api.frkn.org
    description: Production server
  - url: https://frkn.org/api
    description: User registration and authentication server

paths:
  /locations:
    get:
      summary: Get all locations
      tags:
        - peers
      responses:
        "200":
          description: A list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"

  /peer:
    get:
      summary: Get peer information by location
      tags:
        - peers
      parameters:
        - name: location
          in: query
          required: true
          schema:
            type: string
            example: "uk"
      responses:
        "200":
          description: Peer information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeerResponse"

  /stat:
    get:
      summary: Get statistics of nodes
      tags:
        - stats
      responses:
        "200":
          description: A list of node statistics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NodeStat"

  /register:
    post:
      summary: Register a new user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: "example-password"
      responses:
        "200":
          description: User registration response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/RegisterSuccessResponse"
                  - $ref: "#/components/schemas/RegisterErrorResponse"

  /auth:
    post:
      summary: Authenticate a user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: "example-password"
      responses:
        "200":
          description: Authentication response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/AuthSuccessResponse"
                  - $ref: "#/components/schemas/AuthErrorResponse"
          headers:
            Set-Cookie:
              description: JWT token cookie
              schema:
                type: string

components:
  schemas:
    Location:
      type: object
      required: [code, name]
      properties:
        code:
          type: string
          example: "uk"
        name:
          type: string
          example: "🇬🇧 uk"

    PeerResponse:
      type: object
      required: [iface, peer]
      properties:
        iface:
          type: object
          required: [address, key, dns]
          properties:
            address:
              type: string
              example: "10.0.0.1/24"
            key:
              type: string
              example: "example-key-123456"
            dns:
              type: string
              example: "8.8.8.8, 8.8.4.4"
        peer:
          type: object
          required: [pubkey, psk, allowed_ips, endpoint]
          properties:
            pubkey:
              type: string
              example: "example-pubkey-abcdef"
            psk:
              type: string
              example: "example-psk-123456"
            allowed_ips:
              type: string
              example: "0.0.0.0/0"
            endpoint:
              type: string
              example: "192.0.2.1:51820"

    NodeStat:
      type: object
      required: [node, hostname, location, type, peers]
      properties:
        node:
          type: string
          example: "example-node-id"
        hostname:
          type: string
          example: "example-hostname"
        location:
          type: object
          required: [code, name]
          properties:
            code:
              type: string
              example: "uk"
            name:
              type: string
              example: "🇬🇧 uk"
        type:
          type: string
          example: "wg"
        peers:
          type: object
          required: [total, live, tx, rx]
          properties:
            total:
              type: integer
              example: 1500
            live:
              type: integer
              example: 75
            tx:
              type: string
              example: "1234567890"
            rx:
              type: string
              example: "0987654321"

    RegisterSuccessResponse:
      type: object
      required: [status, id, created]
      properties:
        status:
          type: string
          enum: [success]
          example: "success"
        id:
          type: string
          format: uuid
          example: "70b57249-a76c-44e0-85c4-cedcb33aa664"
        created:
          type: string
          format: date-time
          example: "2024-07-24T13:49:08.380Z"

    RegisterErrorResponse:
      type: object
      required: [status, message]
      properties:
        status:
          type: string
          enum: [error]
          example: "error"
        message:
          type: string
          example: "Invalid hash"

    AuthSuccessResponse:
      type: object
      required: [status, id, token]
      properties:
        status:
          type: string
          enum: [success]
          example: "success"
        id:
          type: string
          format: uuid
          example: "70b57249-a76c-44e0-85c4-cedcb33aa664"
        token:
          type: string
          example: "example.jwt.token"

    AuthErrorResponse:
      type: object
      required: [status, message]
      properties:
        status:
          type: string
          enum: [error]
          example: "error"
        message:
          type: string
          example: "Invalid hash"
