/**
 * This file was auto-generated by AI.
 * Do not make direct changes to the file.
 */

// https://doc.cryptomus.com/business/payments/creating-invoice
export type CreateInvoiceRequest = {
  amount: string
  currency: string
  order_id: string
  url_success?: string
  url_fail?: string
  is_payment_multiple?: boolean
  lifetime?: number
  payer_currency?: string
  description?: string
  custom_data?: string
}

export type CreateInvoiceResponse =
  | {
      state: 1
      message: string
    }
  | {
      state: 0
      result: {
        uuid: string
        status: string
        amount: string
        payer_currency: string
        payer_amount: string
        url: string
        expiration: string
        order_id: string
        custom_data?: string
      }
    }

// https://doc.cryptomus.com/business/payments/webhook
export type WebhookResponse = {
  type: "payment"
  uuid: string
  order_id: string
  amount: string
  payment_amount: string
  payment_amount_usd: string
  merchant_amount: string
  commission: string
  is_final: boolean
  // https://doc.cryptomus.com/business/payments/payment-statuses
  status:
    | "paid"
    | "paid_over"
    | "wrong_amount"
    | "process"
    | "confirm_check"
    | "wrong_amount_waiting"
    | "check"
    | "fail"
    | "cancel"
    | "system_fail"
    | "refund_process"
    | "refund_fail"
    | "refund_paid"
    | "locked"
  from: string
  wallet_address_uuid: string | null
  network: string
  currency: string
  payer_currency: string
  additional_data: string | null
  convert: {
    to_currency: string
    commission: string | null
    rate: string
    amount: string
  }
  txid: string
  sign: string
}
